[package]
name = "libopencm3_sys"
version = "0.0.1"
authors = ["libopencm3 Developers", "Olivier <olivier@librepush.net>"]
# The licence of the project; inherits libopencm3's licence.
license = "LGPL-3"

build = "build.rs"

[dependencies]


[build-dependencies]
bindgen = "0.37.4"
cc = "1.0"